These sets of codes were made on 7/5/2025. The objective was to estimate the drainage rates using the daily reference temperature differential data collected at the 60-cm depth from the Oklahoma Mesonet sites. The loaded files include matlab files containing the temperature differential data (from the MesoSoil database) and a csv file containing the Rosetta3-derived water retention, K0, and L parameters. The Rosetta3 parameters were used to estimate the fitted parameters K0 and L using Rosetta1 run in Windows 98. Using the C2 model in Rosetta1 (old version), the Rosetta3 hydraulic parameters were manually added to generate K0 and L. The dataset where the soil properties (i.e., percent sand, silt, clay, bulk density, and water contents at -33 and -1500 kPa) were taken from MesoSoilv2.0 The codes to generate the Rosetta3 parameters are in K_MesoSoilv2.0.ipynb.

In [ ]:
# Checking the system version used
import sys
print(sys.version)

3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]


In [ ]:
import os
from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/MyDrive/GW_project/GWP/')

In [ ]:
import numpy as np
import pandas as pd
from scipy.io import loadmat    # handles matlab files

In [32]:
# Loading the csv file containing the hydraulic parameters, K0, and L.
df = pd.read_csv('/content/drive/MyDrive/Drainage_estimate/Rosetta3_with_K0_and_L.csv', skiprows=1)

# Extracting every column in the file.
Site_ID = df['Site_ID']
theta_r = df['theta_r[cm3/cm3]']
theta_s = df['theta_s[cm3/cm3]']
alpha = df['alpha[1/kPa]']
n = df['n']
m = df['m']
Ks = df['Ks[cm/day]']
K0 = df['K0[cm/day]']
L = df['L']

# Loading the matlab files
mat_folder = '/content/drive/MyDrive/Drainage_estimate/daily_deltaT'

# Putting all the matlab files in the directory while sorting them alphabetically
mat_files = sorted([f for f in os.listdir(mat_folder) if f.endswith('.mat')])

for mat_file in mat_files:
    file_path = os.path.join(mat_folder, mat_file)
    data = loadmat(file_path)

    print(f"\n--- Contents of {mat_file} ---")

    for key, value in data.items():
        if key.startswith('__'):
            continue  # Skip metadata keys

        print(f"Variable: {key}")
        print(f"  Type: {type(value)}")

        try:
            print(f"  Shape: {value.shape}")
            print(f"  First few values: {value[:20].flatten()}\n")
        except Exception as e:
            print(f"  Could not display values: {e}")
            print(f"  Raw value:\n{value}\n")

Streaming output truncated to the last 5000 lines.
 array([[136]], dtype=uint8) array([[nan]]) array([[nan]]) array([[nan]])
 array([[729161]], dtype=int32) array([[137]], dtype=uint8) array([[nan]])
 array([[nan]]) array([[nan]]) array([[729162]], dtype=int32)
 array([[138]], dtype=uint8) array([[nan]]) array([[nan]]) array([[nan]])
 array([[729163]], dtype=int32) array([[139]], dtype=uint8) array([[nan]])
 array([[nan]]) array([[nan]]) array([[729164]], dtype=int32)
 array([[140]], dtype=uint8) array([[nan]]) array([[nan]]) array([[nan]])
 array([[729165]], dtype=int32) array([[141]], dtype=uint8) array([[nan]])
 array([[nan]]) array([[nan]]) array([[729166]], dtype=int32)
 array([[142]], dtype=uint8) array([[nan]]) array([[nan]]) array([[nan]])
 array([[729167]], dtype=int32) array([[143]], dtype=uint8) array([[nan]])
 array([[nan]]) array([[nan]]) array([[729168]], dtype=int32)
 array([[144]], dtype=uint8) array([[nan]]) array([[nan]]) array([[nan]])
 array([[729169]], dtype=int32)